# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: YmNmMTQzMTE0NTgwNmU4YTRjMThmMzE1NzI3NjEyZWY3OTUxOTQ2ZWIwMTM2MzdhMjc2MWQ0MGE3OTRhODZhZTIzNTJmM2E4NGI2NmEyZjNiMDMwZDhjZDY2MTAyY2E5ZGYyNzRmOGEyZGVhZGRlYWQ3MjExOWU3N2VlMzFkNTM=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
